# Introduction to pandas

## Why use pandas?

*Addresses some shortcomings of NumPy:*

1.  Data is organized in *variables* and *observations*

2.  Each variable is permitted to have a *different* data type (integers, floats, strings, ...)

3.  Can select observations based on *labels* (e.g., time or date)

4.  Supports aggregation & reduction functions applied to *subsets* of data

5.  Many convenient data import / export functions

## Why not?

1.  NumPy is faster for low-level computing on homogeneous data
2.  pandas can consume lots of memory
3.  pandas can be slow with large data sets (millions of observations)

## Resources

- [pandas cheat sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

***
## Creating pandas data structures

pandas has two main data structures:

1.  [`Series`](https://pandas.pydata.org/docs/reference/api/pandas.Series.html):
    observations of a *single* variable.
2.  [`DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html):
    container for *several* variables.

*Example: Create Series from 1-dimensional NumPy array*

In [4]:
import pandas as pd

#Create some with numpy
import numpy as np

data = np.arange(5, 10)

#Create a series from a numpy arrray
s = pd.Series(data)
s

0    5
1    6
2    7
3    8
4    9
dtype: int64

*Example: Create DataFrame from NumPy array*

-   We can create 2-dimensional arrays from 1-dimensional ones with 
    [`reshape()`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [5]:
data2d = np.arange(15).reshape(5, 3)
data2d

#Create a Dataframe from 2d array
df = pd.DataFrame(data2d)
df

    0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

*Example: Create DataFrame with non-homogeneous data from dictionary*

In [6]:
import numpy as np
import pandas as pd

# Create demo data for two individuals:

# Names (strings)
names = ['Alice', 'Bob']

# Birth dates (datetime objects)
bdates = pd.to_datetime(['1985-01-01', '1997-05-12'])

# Incomes (floats)
incomes = np.array([600000, np.nan])  # code missing income as NaN

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Create a pandas `Series` which contains the characters `'a'`, `'b'`, and `'c'`.
</div>
<span style="display: none;">YourTurnEnd</span>

In [7]:
lst = ['a', 'b', 'c']
s = pd.Series(lst)

***
## Loading data with pandas

The most important input/output functions are:

-   [`read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html),
    [`to_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html):
    Read or write CSV text files.
-   [`read_fwf()`](https://pandas.pydata.org/docs/reference/api/pandas.read_fwf.html):
    Read data with fixed field widths, i.e., text data
    that does not use delimiters to separate fields.
-   [`read_excel()`](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html),
    [`to_excel()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html):
    Read or write Excel spreadsheets.
-   [`read_stata()`](https://pandas.pydata.org/docs/reference/api/pandas.read_stata.html),
    [`to_stata()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_stata.html):
    Read or write Stata's `.dta` files.
-   [`read_json()`](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html),
    [`to_json()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html#pandas.DataFrame.to_json):
    Read or write JSON files (lightweight machine-readable text files, often produced by LLMs)

*Example: Load data using `read_csv()`*

In [8]:
# Use files in the local data/ directory
DATA_PATH = '../../data'

In [17]:
# File name to FRED_annual.csv
file = f'{DATA_PATH}titanic.csv'
file

'../../datatitanic.csv'

In [18]:
data = pd.read_csv(file, sep=',')
data

FileNotFoundError: [Errno 2] No such file or directory: '../../datatitanic.csv'

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use the pandas functions listed above to import data from the following files located in the `data` folder:

1. `titanic.csv`
2. `FRED/FRED_annual.xlsx`

To load Excel files, you need to have the package `openpyxl` installed.
</div>
<span style="display: none;">YourTurnEnd</span>

In [12]:
Fred_excel = f'{DATA_PATH}/FRED/FRED_annual.xlsx'
data_Fred_excel = pd.read_excel(Fred_excel)
data_Fred_excel

    Year      GDP    CPI  UNRATE  FEDFUNDS  INFLATION
0   1954   2877.7   26.9     5.6       1.0        NaN
1   1955   3083.0   26.8     4.4       1.8  -0.371747
2   1956   3148.8   27.2     4.1       2.7   1.492537
3   1957   3215.1   28.1     4.3       3.1   3.308824
4   1958   3191.2   28.9     6.8       1.6   2.846975
..   ...      ...    ...     ...       ...        ...
67  2021  21532.4  271.0     5.4       0.1   4.673619
68  2022  22075.9  292.6     3.6       1.7   7.970480
69  2023  22723.7  304.7     3.6       5.0   4.135338
70  2024  23358.4  313.7     4.0       5.1   2.953725
71  2025  23850.4  322.0     4.3       4.2   2.645840

[72 rows x 6 columns]

***
## Viewing data

Methods for inspecting (parts of) a `DataFrame`:

- [`info()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html):
  print observation counts, columns, and data types
- [`head()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html):
  print the first few rows
- [`tail()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html):
  print the last few rows
- [`describe()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html):
  print summary statistics for *numerical* data
- [`value_counts()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html):
  tabulate observation counts for categorical data

- [`set_option()`](https://pandas.pydata.org/docs/reference/api/pandas.set_option.html):
  set pandas display options

*Example: Titanic data set*

Columns present in the file `titanic.csv`:

1.  `PassengerId`
2.  `Survived`: indicator whether the person survived
3.  `Pclass`: accommodation class (first, second, third)
4.  `Name`: Name of passenger (last name, first name)
5.  `Sex`: `male` or `female`
6.  `Age`
7.  `Ticket`: Ticket number
8.  `Fare`: Fare in pounds
9.  `Cabin`: Deck + cabin number
10. `Embarked`: Port at which passenger embarked:
    `C` - Cherbourg, `Q` - Queenstown, `S` - Southampton

*Example: Viewing data with `head()` and `tail()`*

### Setting pandas display options

- Use [`set_option()`](https://pandas.pydata.org/docs/reference/api/pandas.set_option.html) to configure how much data pandas displays by default.

In [13]:
# Set the line width to 120 characters (default: 80)
pd.set_option('display.width', 120)
# Show up to 100 rows (default: 60)
pd.set_option('display.max_rows', 5)

In [14]:
data_Fred_excel

    Year      GDP    CPI  UNRATE  FEDFUNDS  INFLATION
0   1954   2877.7   26.9     5.6       1.0        NaN
1   1955   3083.0   26.8     4.4       1.8  -0.371747
..   ...      ...    ...     ...       ...        ...
70  2024  23358.4  313.7     4.0       5.1   2.953725
71  2025  23850.4  322.0     4.3       4.2   2.645840

[72 rows x 6 columns]

### Descriptive statistics

- Use [`describe()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) to compute summary statistics for numerical data.
- Use [`value_counts()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html) to tabulate observation counts for categorical data.
- Use [`info()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html) to tabulate data types and number of non-null rows.

*Example: print summary statistics for numerical data*

*Example: tabulate the number of men and women in the data set*

*Example: Inspect data types with `info()`*

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Using the Titanic data set:

1. Tabulate the number of passengers by boarding port (variable `Embarked`).
2. Count the observations with a missing value for `Embarked`.

   *Hint:* `value_counts()` excludes missing values by default. Use `dropna=False`
   to include them in the table, or use `isna().sum()` to count them separately.
</div>
<span style="display: none;">YourTurnEnd</span>

In [21]:
titanic = f'{DATA_PATH}/titanic.csv'
data_titanic = pd.read_csv(titanic, sep=',')
data_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C
...,...,...,...,...,...,...,...,...,...,...
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q

In [23]:
# 1. Antall passasjerer per boarding-havn
data_titanic['Embarked'].value_counts(dropna=False)

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [26]:
# 2. Antall manglende verdier
n_missing = data_titanic['Embarked'].isna().sum()
n_missing

np.int64(2)

***
## Indexing

pandas supports two types of indexing:

1.  Indexing by position (same as Python containers and NumPy arrays)
2.  Indexing by label, i.e., by the values assigned to the row or column *index*.

pandas indexing is performed either by using brackets `[]`, or by using
[`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)
for label indexing, or
[`.iloc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)
for positional indexing.

Indexing via `[]` can be somewhat confusing:

-   specifying `df['name']` returns the column `name` as a `Series` object.
-   specifying a range such as `df[5:10]` returns the *rows*
    associated with the *positions* 5,...,9.

    **Recommendation:** Don't use this, there are less confusing ways to select rows.

*Example: Selecting a single column*

-   Select column `'Name'` from Titanic data set

*Example: Selecting multiple columns*

-   Select columns `'Name'` and `'Sex'` from Titanic data set
-   Need to specify multiple columns as `list`

In [28]:
data_titanic[['Name', 'Sex']]

                                                  Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
..                                                 ...     ...
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

***
### Creating and manipulating indices


Three main methods to create/manipulate indices:

1.   Create a new `Series` or `DataFrame` object with a custom index
    using the `index` argument.
2.   [`set_index(keys=['column1', ...])`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)
    uses the values of `column1`
    and optionally additional columns as indices, discarding the current index.
3.   [`reset_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html) 
    resets the index to its default value, a sequence
    of increasing integers starting at 0.

#### Creating custom indices

*Example: Create `Series` with custom index*

In [29]:
import pandas as pd
s = pd.Series([[0, 1, 2]], index['a', 'b', 'c'])

NameError: name 'index' is not defined

#### Manipulating indices

-   Default: return a new object; leave the original unchanged.
-   Assign the result back, or use `inplace=True`.
-   With `inplace=True`, both methods return `None`.
-   `set_index()`: `DataFrame` only; `reset_index()`: also `Series`.

*Example: Set DataFrame index from column*

-   Use the
    [`set_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)
    method
-   Optionally specify `append=True` to add as *additional* index levels

In [30]:
# Create demo DataFrame
import pandas as pd

df = pd.DataFrame({'A': [10, 20, 30], 'B': ['a', 'b', 'c']})

In [31]:
df

    A  B
0  10  a
1  20  b
2  30  c

In [32]:
df.set_index('B')

    A
B
a  10
b  20
c  30

*Example: Reset DataFrame index*

-   Use the
    [`reset_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html)
    method
-   Use `drop=True` to discard the old index; otherwise, it becomes a column.

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Read in the following data files from the `data/FRED` folder and manipulate the
`DataFrame` index:

1. Read in the file `FRED_annual.csv` and set the column `Year` as the index.
2. Read in the file `FRED_monthly.csv` and set the columns `Year` and `Month` as the
   index.

Perform the tasks using `inplace=False` and `inplace=True`. What's the difference?

Restore the original (default) index after you are done.
</div>
<span style="display: none;">YourTurnEnd</span>

In [43]:
file_annual = f'{DATA_PATH}/FRED/FRED_annual.csv'
file_monthly = f'{DATA_PATH}/FRED/FRED_monthly.csv'

df_annual = pd.read_csv(file_annual)
df_monthly = pd.read_csv(file_monthly)

In [44]:
df_annual = df_annual.set_index('Year', inplace=False)

In [45]:
df_annual

          GDP    CPI  UNRATE  FEDFUNDS  INFLATION
Year
1954   2877.7   26.9     5.6       1.0        NaN
1955   3083.0   26.8     4.4       1.8       -0.4
...       ...    ...     ...       ...        ...
2024  23358.4  313.7     4.0       5.1        3.0
2025  23850.4  322.0     4.3       4.2        2.6

[72 rows x 5 columns]

In [46]:
df_monthly = df_monthly.set_index(['Year', 'Month'], inplace=False)

In [47]:
df_monthly

                  DATE    CPI  UNRATE  FEDFUNDS  REALRATE  LFPART
Year Month
1948 1      1948-01-01   23.7     3.4       NaN       NaN    58.6
     2      1948-02-01   23.7     3.8       NaN       NaN    58.9
...                ...    ...     ...       ...       ...     ...
2025 11     2025-11-01  325.1     4.5       3.9       1.0    62.5
     12     2025-12-01  326.0     4.4       3.7      -0.1    62.4

[936 rows x 6 columns]

***
### Selecting elements

Recommended rules for indexing:

1.  Use `df['name']` to select *columns*.
2.  Use
    [`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)
    to select by label.
3.  Use
    [`.iloc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)
    to select by position.

*Demo data set used for this section:*

In [ ]:
# Create demo data with 3 columns and 5 rows

# Column labels
columns = ['X', 'Y', 'Z']
# Row labels
rows = ['a', 'b', 'c', 'd', 'e']

values = np.arange(len(rows))

# Create data dictionary using a list comprehension
data = {col: [f'{col}{val}' for val in values] for col in columns}

# Create DataFrame from dictionary
df = pd.DataFrame(data, index=rows)

In [54]:
df

    X   Y   Z
a  X0  Y0  Z0
b  X1  Y1  Z1
c  X2  Y2  Z2
d  X3  Y3  Z3
e  X4  Y4  Z4

**Selection by label**

-   Use
    [`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)
    to select rows and/or columns *by label*
-   Can use *slicing* where last element is *included*

In [55]:
df.loc['a':'c', 'X':'Y']

    X   Y
a  X0  Y0
b  X1  Y1
c  X2  Y2

**Selection by position**

-   Use
    [`.iloc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)
    to select rows and/or columns *by position*
-   Reset the demo index to default integers before the exercise.

In [56]:
df.iloc[0:3]

    X   Y   Z
a  X0  Y0  Z0
b  X1  Y1  Z1
c  X2  Y2  Z2

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Using the DataFrame `df` we created above:

1. Compare `df.loc[0:3]` and `df.iloc[0:3]`. How many rows does each select?
   Predict the results before running the code.
2. Compare `df.loc[-1]` and `df.iloc[-1]`. What happens in each case, and why?
</div>
<span style="display: none;">YourTurnEnd</span>

**Boolean indexing**

-   Select elements based on whether some condition is true
-   Works with `[]` and `.loc[]`

In [57]:
titanic = f'{DATA_PATH}/titanic.csv'
data_titanic = pd.read_csv(titanic, sep=',')

In [58]:
# Create a boolean mask selecting all with embarked == S
mask = data_titanic['Embarked'] == 'S'

In [60]:
data_titanic[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.925,NaN,S
...,...,...,...,...,...,...,...,...,...,...
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.450,NaN,S

*Example: Boolean indexing with Titanic data*

- Select all rows of passengers who embarked in Southampton (`'Embarked'` equals `'S'`)

*Example: Multiple conditions with logical and/or*

- Select all rows of *male* passengers (`'Sex'` equals `'male'`) who embarked in Southampton (`'Embarked'` equals `'S'`)

*Example: Using `isin()`*

- Select all rows of passengers who embarked either in Southampton or Queenstown
  (`'Embarked'` equals `'S'` or `'Q'`)

*Example: Using `query()`*

- Select all rows of passengers who embarked in Southampton (`'Embarked'` equals `'S'`) and are older than 70

In [63]:
data_titanic.query('Embarked == "S" | Age > 70')

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.925,NaN,S
...,...,...,...,...,...,...,...,...,...,...
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.450,NaN,S

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Load the Titanic passenger data set `data/titanic.csv` and select the following subsets of data:

1. Select the 10th to 20th (inclusive) rows of the `DataFrame`.
2. Using `query()`, select the sub-sample of female passengers aged 30 to 40. Display
   only the columns `Name`, `Age`, and `Sex` (in that order).
3. Repeat the last exercise without using `query()`.
4. Select all men who embarked in Queenstown or Cherbourg.
</div>
<span style="display: none;">YourTurnEnd</span>

***
## Working with time series data

-   pandas indices can be date or datetime data types
-   Use
    [`date_range()`](https://pandas.pydata.org/docs/reference/api/pandas.date_range.html)
    to create a range of dates
-   Use
    [`to_datetime()`](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html)
    to convert existing data to datetime format

*Example: Creating a date index*

-   Create a demo data set of daily observations for the first 3 months of 2026

In [ ]:
# Start and end dates used for demo data set
start = '2026-01-01'
end = '2026-03-31'

*Example: Select particular date*

-   Select observation from January 1, 2026

*Example: Select date range*

- Select first 5 days in January 2026

*Example: Use a partial index*

- Select all of January 2026

### Lags, differences, and other useful transformations

Methods to shift/difference observations along time dimension:

- [`shift()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.shift.html):
  shifts values to create leads/lags; keeps the index unchanged by default
- [`diff()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.diff.html):
  computes absolute differences over a given period
- [`pct_change()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.pct_change.html):
  computes fractional changes; multiply by 100 for percentages

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use the data from the `data/FRED` folder to perform the following tasks:

1. Read in the file `FRED_annual.csv` and set the column `Year` as the index.
2. Compute annual inflation as the percentage change of the consumer price
   index (column `CPI`). Use `pct_change()` and multiply by 100 to express
   inflation as a percentage.
</div>
<span style="display: none;">YourTurnEnd</span>